[tool.poetry]
name = "jorgelavielle-vituales-bot"
version = "0.1.0"
description = ""
authors = ["jorgelavielle <lavielle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10.1"
python-telegram-bot = "^13.9"
pillow = "^7.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"