[tool.poetry.]
name = "jorgelavielle-bot2"
version = "0.1.0"
description = ""
author = "jorgelavielle-bot2"

[tool.poetry.dependencies]
python = "3.10.1"
python-telegram-bot = "13.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-bakend = "poetry.masonry.api"